# Dockerfile.streamlit
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

# Installer les dépendances
RUN apt-get update && \
    apt-get install -y build-essential && \ 
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY . /app

EXPOSE 8501

# Pas de CMD ici car il sera défini par docker-compose