services:
  fastapi: # Renommé de fastapi_app pour la simplicité, mais "fastapi_app" est aussi valide
    build:
      context: .
      dockerfile: Dockerfile.fastapi # Utilisez Dockerfile.fastapi
    container_name: langchain_fastapi
    ports:
      - "8000:8000"
    env_file: # Préférable à "environment" pour les clés sensibles et la réutilisabilité
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    working_dir: /app # Ajouté pour être explicite

  streamlit: # Renommé de streamlit_app
    build:
      context: .
      dockerfile: Dockerfile.streamlit # Utilisez Dockerfile.streamlit
    container_name: langchain_streamlit
    volumes:
      - .:/app
    env_file: # Préférable à "environment"
      - .env
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    restart: unless-stopped
    depends_on:
      - fastapi
    working_dir: /app # Ajouté pour être explicite